version: "3"

services:
  anti_bruteforce:
    build:
      dockerfile: ./build/Dockerfile
      context: ../
    depends_on:
      - redis
    environment:
      - ANTI_BRUTEFORCE_LISTEN_ADDR=0.0.0.0:8080
    restart: on-failure
    ports:
      - "8080:8080"

  redis:
    image: redis
    ports:
      - '6379:6379'